name: Publish to Docker
on:
  push:
    tags:
      - '*'
    branches:
      - 'master'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to SoftwareAG container registry
        uses: docker/login-action@v2
        with:
          registry: sagcr.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to DockerHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHIO_TOKEN }}  
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository_owner }}/wxxoev
            ghcr.io/${{ github.repository_owner }}/wxxoev
          tags: |
            type=ref,event=tag
            type=sha          
      - name: Build container
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}           
