name: Publish to Docker
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: sag-nokroeger
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: sag-nokroeger/publish-packages/wxxoev
          tag_with_sha: true
          tag_with_ref: true
